import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { reactNodeSchemaType } from "@/lib/schema";
import HeaderPage from "@/components/custom/header";
import createClient from "@/lib/supabase/server";
import { Toaster } from "@/components/ui/toast";
import RoleProvider from "@/contexts/role-provider";
import UserMetadataProvider from "@/contexts/role-provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: reactNodeSchemaType) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <div className="mx-auto container">
          <UserMetadataProvider user={data?.claims.user_metadata}>
            <HeaderPage user={data?.claims.user_metadata}  />
            <div className="container mx-auto my-8">
              {children}
            </div>
          </UserMetadataProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
