import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactNodeType } from "@/lib/schema";
import HeaderPage from "@/components/custom/header";
import { Toaster } from "@/components/ui/toast";
import UserMetadataProvider from "@/contexts/auth-provider";
import { ViewTransition } from "react";
import { createClient } from "@/lib/supabase/server";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: ReactNodeType) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <UserMetadataProvider payload={data?.claims}>
          <ViewTransition>
            <HeaderPage user={data?.claims.user_metadata} />
            <div className="mx-auto container px-6">
              <div className="container mx-auto my-8">{children}</div>
            </div>
          </ViewTransition>
        </UserMetadataProvider>
        <Toaster />
      </body>
    </html>
  );
}
