drop extension if exists "pg_net";

create type "public"."roles" as enum ('ADMIN', 'USER');


  create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "title" character varying not null,
    "description" text,
    "image_link" character varying,
    "created_by" uuid default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
      );


alter table "public"."events" enable row level security;


  create table "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid,
    "updated_at" timestamp with time zone,
    "roles" public.roles default 'USER'::public.roles
      );


alter table "public"."user_roles" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."events" add constraint "events_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE RESTRICT not valid;

alter table "public"."events" validate constraint "events_created_by_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_auth_login(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
  declare 
    claims jsonb;
    user_metadata jsonb;
    user_role public.user_roles.roles%type;
begin
  claims := event->'claims';
  user_metadata := claims->'user_metadata';

  select roles into user_role from public.user_roles where auth_id = (claims->>'sub')::uuid;

  if user_role is not null then 
    user_metadata := jsonb_set(user_metadata, '{user_role}', to_jsonb(user_role));
  else
    user_metadata := jsonb_set(user_metadata, '{user_role}', to_jsonb('null'));
  end if;

  claims := jsonb_set(claims, '{user_metadata}', user_metadata);
  event := jsonb_set(event, '{claims}', claims);

  return event;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.user_roles (auth_id)
  values (new.id);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select (auth.jwt() ->> 'user_role') = 'ADMIN'
$function$
;

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant references on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "supabase_auth_admin";


  create policy "Enable delete for admin only"
  on "public"."events"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "Enable insert for authenticated users only"
  on "public"."events"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."events"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users own records only"
  on "public"."events"
  as permissive
  for update
  to authenticated
using (true)
with check ((auth.uid() = created_by));



  create policy "Allow auth admin to read user roles"
  on "public"."user_roles"
  as permissive
  for select
  to supabase_auth_admin
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


