
  create table "public"."subscribed_events" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null default auth.uid(),
    "event_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."subscribed_events" enable row level security;

alter table "public"."events" add column "available_slot" smallint not null;

alter table "public"."events" alter column "max_slot" set not null;

CREATE UNIQUE INDEX subscribed_events_pkey ON public.subscribed_events USING btree (id);

alter table "public"."subscribed_events" add constraint "subscribed_events_pkey" PRIMARY KEY using index "subscribed_events_pkey";

alter table "public"."subscribed_events" add constraint "subscribed_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."subscribed_events" validate constraint "subscribed_events_event_id_fkey";

alter table "public"."subscribed_events" add constraint "subscribed_events_user_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."subscribed_events" validate constraint "subscribed_events_user_fkey";

grant delete on table "public"."subscribed_events" to "anon";

grant insert on table "public"."subscribed_events" to "anon";

grant references on table "public"."subscribed_events" to "anon";

grant select on table "public"."subscribed_events" to "anon";

grant trigger on table "public"."subscribed_events" to "anon";

grant truncate on table "public"."subscribed_events" to "anon";

grant update on table "public"."subscribed_events" to "anon";

grant delete on table "public"."subscribed_events" to "authenticated";

grant insert on table "public"."subscribed_events" to "authenticated";

grant references on table "public"."subscribed_events" to "authenticated";

grant select on table "public"."subscribed_events" to "authenticated";

grant trigger on table "public"."subscribed_events" to "authenticated";

grant truncate on table "public"."subscribed_events" to "authenticated";

grant update on table "public"."subscribed_events" to "authenticated";

grant delete on table "public"."subscribed_events" to "service_role";

grant insert on table "public"."subscribed_events" to "service_role";

grant references on table "public"."subscribed_events" to "service_role";

grant select on table "public"."subscribed_events" to "service_role";

grant trigger on table "public"."subscribed_events" to "service_role";

grant truncate on table "public"."subscribed_events" to "service_role";

grant update on table "public"."subscribed_events" to "service_role";